### ISSUE TITLE
[Big, Hard] Package Releases Automation

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#44]
trypear/pearai-app-archive#18 

We have a manual process for packaging + releasing 
1. packaging: https://github.com/trypear/pearai-app/blob/main/CONTRIBUTING.md#packaging
2. releasing: https://docs.google.com/document/d/1hZahz2UNrtZOgHZkquqNO7Jfoe0Pd0OA7Ud16ts_AKs/edit#heading=h.4tjqh0b1bbef

It requires us to depend on contributors to help us package on the actual OS

We need to figure out a way to 
1. automate this and
3. package all OS versions from a single machine

I think vscode has a way of doing this on cloud based?

**Comment by eli-front** [comment]
I don't have time for a full PR, but I would suggest checking out [Electron Forge](https://www.electronforge.io/) & then doing something like their suggested [github action](https://github.com/electron-forge/distributable-action). There are a few pre-builts for making releases like [action-gh-release](https://github.com/softprops/action-gh-release), but it's not too much work to roll that yourself
```yaml
inputs:
  macos-cert-importer:
    description: 'Path to script used to import the macOS P12 certificate used to sign the app.'
    default: '$GITHUB_ACTION_PATH/scripts/import-macos-cert.sh'
    required: false
  macos-cert-p12:
    description: 'The base64-encoded contents of the macOS P12 certificate used to sign the app. Used by the default `macos-cert-importer` script.'
    required: false
  macos-cert-password:
    description: 'The password used to unlock the signing certificate so that it can be imported into the keychain.'
    required: false
  node-installer:
    description: 'Which Node.js package manager to use (`yarn` or `npm`). Defaults to detecting which package manager was used on the app via `yarn-or-npm` (which is used by Electron Forge).'
    required: false
  target-arch:
    description: 'The target architecture for the Electron app distributable.'
    required: false
  target-maker:
    description: 'The target Electron Forge maker module which generates the distributable artifacts. For example, @electron-forge/maker-deb'
    required: true
  target-platform:
    description: 'The target platform for the Electron app distributable.'
    required: true
  windows-cert-filename:
    description: 'Path to the PFX certificate generated from the windows-cert-p12 input. Provided to a JavaScript-based Forge config as `process.env.WINDOWS_CERT_FILENAME`.'
    default: 'windows-certificate.pfx'
  windows-cert-importer:
    description: 'Path to script used to import the macOS P12 certificate used to sign the app.'
    default: 'node $GITHUB_ACTION_PATH/scripts/import-windows-cert.js'
    required: false
  windows-cert-p12:
    description: 'The base64-encoded contents of the Windows P12 certificate used to sign the app for Squirrel and AppX makers. Used by the default `windows-cert-importer` script.'
    required: false
  windows-cert-password:
    description: 'The password used to unlock the signing certificate so that it can sign the distributables. Provided to a JavaScript-based Forge config as `process.env.WINDOWS_CERT_PASSWORD`.'
    required: false

runs:
  using: composite
  steps:
    - name: Install platform dependencies
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/platform-dependencies.sh
      env:
        TARGET_MAKER: ${{ inputs.target-maker }}
    - name: Install Node.js dependencies
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/install.sh
      env:
        NODE_INSTALLER: ${{ inputs.node-installer }}
    - name: Set up macOS signing certificate
      shell: bash
      run: ${{ inputs.macos-cert-importer }}
      env:
        MACOS_CERT_PASSWORD: ${{ inputs.macos-cert-password }}
        MACOS_CERT_P12: ${{ inputs.macos-cert-p12 }}
    - name: Set up Windows signing certificate
      shell: bash
      run: ${{ inputs.windows-cert-importer }}
      env:
        WINDOWS_CERT_FILENAME: ${{ inputs.windows-cert-filename }}
        WINDOWS_CERT_P12: ${{ inputs.windows-cert-p12 }}
    - name: Create app distributable
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/make.sh
      env:
        NODE_INSTALLER: ${{ inputs.node-installer }}
        TARGET_ARCH: ${{ inputs.target-arch }}
        TARGET_MAKER: ${{ inputs.target-maker }}
        TARGET_PLATFORM: ${{ inputs.target-platform }}
        WINDOWS_CERT_FILENAME: ${{ inputs.windows-cert-filename }}
        WINDOWS_CERT_PASSWORD: ${{ inputs.windows-cert-password }}
```
